version: "3.3"
services:
  mongo:
    image: mongo
    environment:
      - PUID=1000
      - PGID=1000
      - MONGO_INITDB_ROOT_USERNAME=eeriegg
      - MONGO_INITDB_ROOT_PASSWORD=eerieggpassword
    ports:
      - 27217:27017
    restart: always
  redis:
    image: redis
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6337:6379"
    restart: always
