export enum WebsocketErrorMessage {
  INVALID_MESSAGE = "INVALID_MESSAGE",
  INVALID_DATA = "INVALID_DATA",
  INVALID_CHANNEL = "INVALID_CHANNEL",
  INVALID_ACTION = "INVALID_ACTION",
  UNAUTHORIZED = "UNAUTHORIZED",
  UNKNOWN_CLIENT = "UNKNOWN_CLIENT",
}
