export enum WebsocketErrorMessage {
  INVALID_MESSAGE = "INVALID_MESSAGE",
  INVALID_DATA = "INVALID_DATA",
  INVALID_CHANNEL = "INVALID_CHANNEL",
  INVALID_ACTION = "INVALID_ACTION",
  UNAUTHORIZED = "UNAUTHORIZED",
  UNKNOWN_CLIENT = "UNKNOWN_CLIENT",
}
export enum WalletErrorMessage {
  CREATION_ERROR = "CREATION_ERROR",
  CREATION_ERROR_HOOK = "CREATION_ERROR_HOOK",
  UNAUTHORIZED = "UNAUTHORIZED",
  ALREADY_CREATED = "ALREADY_CREATED",
}

export enum BalanceErrorMessage {
  UPDATE_FAILED = "UPDATE_FAILED",
}
